### ISSUE TITLE
tittle berilmagan

### ISSUE THREAD

**Issue by oyatillo0201** [muslim0602/intro-form#2]
sizdagi holat:
![image](https://user-images.githubusercontent.com/102718840/168989205-4ac91d9e-7b7f-42f6-9af7-db31d8e6757b.png)

kutilgan natija:
![image](https://user-images.githubusercontent.com/102718840/168989331-5b6ea49c-1f69-4097-80cc-1598db6f78d8.png)

**Comment by muslim0602** [comment]
😊
